### ISSUE TITLE
Integrate Logo

### ISSUE THREAD

**Issue by horikandthepurpleshrooms** [codecontrive/jobhub-react#7]
Simple logo integration on the landing page. Should be user friendly and minimalist.

**Comment by horikandthepurpleshrooms** [comment]
I integrated one version of logo for the app in the place of the h1 tag that kept the title from the main screen. I also added some minor changes in the `next.config.js` file. I also added two new packages, [next-compose-plugins](https://github.com/cyrilwanner/next-compose-plugins) and [next-optimized-images](https://github.com/cyrilwanner/next-optimized-images).  I opened a PR with this changes.

#### For the future I could add more assets or change the logo design.

**Comment by rrstux** [comment]
Removed the feature tag due to the existence of the default enhancement tag.
